### ISSUE TITLE
Updating Model 3 DBC ?

### ISSUE THREAD

**Issue by redosk** [thezim/DBCTools#1]
Hi,

Could it be possible to update Model 3 DBC ?
I'm especially interested in the alert matrices and DAS signals (but I'm wondering if in the latest versions DAS signals are still presents on the CAN buses).

**Comment by thezim** [comment]
The latest Tesla Model 3 DBC file is [here](https://github.com/joshwardell/model3dbc). I am not the developer of the code in this repository. All code and files were copied here from a forgotten internet source for prosperity. @joshwardell is a wealth of information on the [forum](https://teslaownersonline.com/threads/diagnostic-port-and-data-access.7502/) if you are looking for specific information.

**Comment by redosk** [comment]
Yep ! I knew his DBC but I asked as there are other signals in the one of this repository. 😅
Thanks anyway !

**Comment by thezim** [comment]
I’m pretty sure I got this code from here.

https://brianman.visualstudio.com/_git/DBCTools

I see he had a few commits referencing “TeslaFirmwareDecode”. Code there is pretty old too. Perhaps he might have some further insight on a newer firmware decode.

**Comment by joshwardell** [comment]
Brianman disappeared into the woodwork a while ago, he did some pretty amazing stuff to get that code-derived DBC. Tesla constantly changes the comms though so sadly most of it is out of date
